spring.application.name=CentralAPI

api.client.base-url=${api.model.url}
spring.profiles.active=local

spring.datasource.url=${api.database.url}
spring.datasource.username=${api.database.user}
spring.datasource.password=${api.database.password}

external.api.key=${external.key}
